"""The limits page generates the contract — so its output is checked, not assumed.

`limits-form.html` builds the whole limits.json in the browser: whatever it emits IS the file a user
drives with. That makes it a safety surface, and until now nothing tested it — you could edit
`build()` and quietly drop `power.max_percent`, or (as with `battery.report_below_percent`) add a rule
to the config that the form does not reproduce, so the next regeneration silently loses it.

This runs the page's own JavaScript in node against a small DOM stub, takes `build()`'s output, and:

  * asserts it parses and still carries every key the engine reads — the contract is intact;
  * feeds it to the engine's own `load_limits()` and checks the ceiling that comes back;
  * asserts the shipped `limits.json` and the form agree on `battery.report_below_percent`.

If node is not installed the file skips rather than failing: the repo's other suites stay runnable
with python alone.

Run: venv/bin/python tests/test_limits_form.py
"""
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from types import SimpleNamespace

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
import k250_play as P                                    # noqa: E402

FORM = os.path.join(ROOT, "limits-form.html")
SHIPPED = os.path.join(ROOT, "limits.json")
NODE = shutil.which("node")

PRELUDE = r"""
const els = {};
const registered = [];
function stub(id){
  if (!els[id]) els[id] = { id, value: "", checked: false, textContent: "", style: {},
                            dataset: {}, disabled: false, innerHTML: "",
                            classList: { add(){}, remove(){}, toggle(){} },
                            appendChild(){}, querySelectorAll(){ return []; },
                            addEventListener(){}, insertAdjacentHTML(_, html){ ingest(html); } };
  return els[id];
}
function ingest(html){
  const re = /id="([^"]+)"[^>]*?\svalue="([^"]*)"/g;
  let m;
  while ((m = re.exec(html))) { stub(m[1]).value = m[2]; registered.push(m[1]); }
}
const PRELOAD = %s;
globalThis.setInterval = () => 0;          // the page's timers must not hold node open
globalThis.setTimeout = () => 0;
globalThis.fetch = () => Promise.reject(new Error("no bridge in this test"));
globalThis.document = {
  getElementById: stub,
  createElement: () => ({ style: {}, dataset: {}, textContent: "", value: "",
                          classList: { add(){}, remove(){}, toggle(){} },
                          appendChild(){}, addEventListener(){}, click(){},
                          set href(v){}, set download(v){} }),
  querySelectorAll: () => []
};
for (const [id, v] of Object.entries(PRELOAD)) {
  const e = stub(id);
  if (v.value !== null) e.value = v.value;
  if (v.checked) e.checked = true;
}
"""


def static_inputs(html):
    """The inputs that are real markup (not generated by buildRows): their values are the page's
    defaults, which is exactly what a stranger's generated file would contain."""
    out = {}
    for tag in re.findall(r"<input\b[^>]*>", html, re.S):
        m = re.search(r'id="([^"]+)"', tag)
        if not m:
            continue
        value = re.search(r'value="([^"]*)"', tag)
        out[m.group(1)] = {"value": value.group(1) if value else None,
                           "checked": bool(re.search(r"\bchecked\b", tag))}
    return out


def form_output():
    html = open(FORM, encoding="utf-8").read()
    script = re.search(r"<script>(.*)</script>", html, re.S).group(1)
    preload = static_inputs(html)
    program = PRELUDE % json.dumps(preload) + script + \
        "\nconsole.log(JSON.stringify({json: build(), registered}));\n"
    with tempfile.TemporaryDirectory() as d:
        path = os.path.join(d, "run.js")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(program)
        r = subprocess.run([NODE, path], capture_output=True, text=True, timeout=120)
    if r.returncode != 0:
        raise RuntimeError(f"node failed: {r.stderr.strip()[:400]}")
    out = json.loads(r.stdout.strip().splitlines()[-1])
    out["preload"] = preload          # the page's own HTML defaults, as the stub saw them
    out["script"] = script
    return out


def main():
    if not NODE:
        print("LIMITS FORM: SKIP — node not installed (the other suites still run)")
        return 0

    checks = []
    fails = []

    got = form_output()
    generated, registered = got["json"], got["registered"]
    PRELOAD, script = got["preload"], got["script"]

    checks.append(("buildRows produced the 4x3 channel controls", len(registered) == 12,
                   f"{len(registered)} controls"))

    # 1. it is a file the engine can read at all
    parsed = None
    err = ""
    try:
        parsed = json.loads(generated)
    except Exception as exc:                                          # pragma: no cover
        err = repr(exc)
    checks.append(("the form's output is valid JSON", parsed is not None, err))

    if parsed:
        # 2. every key the engine reads is still there
        for key in ("stop_word", "power", "frequency", "slew", "channels", "session", "safety",
                    "battery"):
            checks.append((f"generated file has {key}", key in parsed, ""))
        # The acknowledgement is a per-session GATE now (unticked on every page load,
        # and it holds Run shut until ticked). The generated file records it honestly:
        # true only if it is ticked at the moment you press Download / Copy — and the
        # Apply path never writes this field at all, so a page that has not been
        # ticked cannot silently un-acknowledge the file on disk.
        checks.append(("the generated file records the acknowledgement honestly",
                       parsed.get("safety", {}).get("hard_stops_acknowledged")
                       is (PRELOAD.get("ack", {}).get("checked") is True),
                       parsed.get("safety", {}).get("hard_stops_acknowledged")))
        checks.append(("the page ships with the acknowledgement unticked",
                       PRELOAD.get("ack", {}).get("checked") is False,
                       PRELOAD.get("ack", {}).get("checked")))
        checks.append(("Apply never sends the acknowledgement field",
                       "ack:" not in re.sub(r"\s+", " ",
                                            script.split("function limitsBody")[1]
                                            .split("}")[0]) if "function limitsBody" in script else False,
                       "limitsBody payload"))
        checks.append(("the file on disk keeps its own acknowledgement",
                       json.load(open(SHIPPED)).get("safety", {}).get("hard_stops_acknowledged") is True,
                       json.load(open(SHIPPED)).get("safety", {}).get("hard_stops_acknowledged")))
        checks.append(("hard stops still listed",
                       len(parsed.get("safety", {}).get("hard_stops", [])) >= 6, ""))

        # 3. the battery reporting rule, which is why this test exists
        batt = parsed.get("battery", {})
        checks.append(("generated battery.report_below_percent is a number 0-100",
                       isinstance(batt.get("report_below_percent"), (int, float))
                       and 0 <= batt["report_below_percent"] <= 100,
                       batt.get("report_below_percent")))
        checks.append(("generated battery threshold defaults to 10",
                       batt.get("report_below_percent") == 10, batt.get("report_below_percent")))
        checks.append(("generated battery note says it is not a limit",
                       "not a limit" in str(batt.get("note", "")).lower(), ""))

        # 4. the engine accepts the generated file and honours its ceiling
        with tempfile.TemporaryDirectory() as d:
            path = os.path.join(d, "limits.json")
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(generated)
            lim = P.load_limits(path)
            cli = SimpleNamespace(hardcap=None, max_rate=None, ma_top=None, channel_caps="",
                                  limits=None)
            hard, rate, freq, caps = P.apply_limits(cli, lim)
            want = parsed["power"]["max_percent"]
            checks.append(("the engine reads the generated ceiling",
                           hard == float(want), f"{hard} vs {want}"))
            checks.append(("a CLI ceiling cannot raise the generated one",
                           P.apply_limits(SimpleNamespace(hardcap=99, max_rate=None, ma_top=None,
                                                          channel_caps="", limits=None), lim)[0]
                           == float(want), ""))
            want_caps = {k: {kk: vv for kk, vv in v.items() if vv is not None}
                         for k, v in parsed["channels"]["per_channel"].items()}
            want_caps = {k: v for k, v in want_caps.items() if v}
            got_caps = json.loads(caps) if caps else {}
            checks.append(("the engine reads the generated per-channel caps",
                           got_caps == want_caps, f"{got_caps} vs {want_caps}"))

    # 5. the form and the shipped file must agree, or one of them is lying
    shipped = json.load(open(SHIPPED, encoding="utf-8"))
    checks.append(("shipped limits.json carries the battery rule",
                   "battery" in shipped, ""))
    checks.append(("form and shipped limits.json agree on the battery threshold",
                   shipped.get("battery", {}).get("report_below_percent")
                   == json.loads(generated).get("battery", {}).get("report_below_percent"),
                   f"{shipped.get('battery', {}).get('report_below_percent')} vs "
                   f"{json.loads(generated).get('battery', {}).get('report_below_percent')}"))

    for label, ok, note in checks:
        print(f"  {'ok  ' if ok else 'FAIL'}  {label}" + (f"  — {note}" if note else ""))
        if not ok:
            fails.append(label)

    print()
    if fails:
        print(f"LIMITS FORM: FAIL ({len(fails)} of {len(checks)} checks)")
        return 1
    print(f"LIMITS FORM: PASS — all {len(checks)} checks")
    return 0


if __name__ == "__main__":
    sys.exit(main())
